### ISSUE TITLE
Add docker 1.12 support

### ISSUE THREAD

**Issue by pepijnblom** [getcarina/dvm#127]
I'm running the open beta of Docker on OS X El Capitan (10.11.5) and have not been able to get dvm to use because this version is not supported.

Could support be added for 1.12?

**Comment by carolynvs** [comment]
Normally you can get access to prereleases by running `dvm install experimental`, unfortunately that's not working right now because the URL we are building to download experimental versions needs to be updated to use their new archived releases format.

I'll get dvm updated and a new version pushed out soon. Thanks for the heads up!

**Comment by carolynvs** [comment]
dvm 0.6.3 contains the fix for this. First run `dvm upgrade` to get the latest version of dvm*, then run `dvm install experimental` to install the latest nightly build of the Docker client.

\* _if you installed via homebrew, I've [submitted the new version](https://github.com/Homebrew/homebrew-core/pull/3093) but it hasn't been merged yet_
