### ISSUE TITLE
Configure .bashrc/.zshrc during install script

### ISSUE THREAD

**Issue by rveguilla** [getcarina/dvm#145]
It will be great if dvm (like nvm) took care of adding the `source $HOME/.dvm/dvm.sh` to .bashrc/.zshrc.

**Comment by carolynvs** [comment]
While I understand why this would be useful, editing people's dotfiles isn't something I want to get involved in at this time. 😃

**Comment by rveguilla** [comment]
I understand this is not something you probably want to invest time on right now, but I think you should  seriously considered as a future enhancement. Other tools on this space (nvm, sdkman) have being doing this for a long time I will say I think it's part of the expected behavior.

**Comment by ibigbug** [comment]
I think keep user's rc file clean is the point. Since I don't what will nvm like tools do with which of my rc file, bashrc or zshrc? .profile or .zprofile? It's super easy to get those files mess up without a user confirm. So I don't think your point is an expected behavior, on the contrast, I think it's a bit 'dirty' work.
