### ISSUE TITLE
DOCKER_CLIENT_VERSION?

### ISSUE THREAD

**Issue by everett-toews** [getcarina/dvm#83]
Now that the Docker CLI keys off the env var `DOCKER_API_VERSION ` (see [Environment Variables](https://docs.docker.com/engine/reference/commandline/cli/#environment-variables)), should `dvm` key off the env var `DOCKER_CLIENT_VERSION` instead of just `DOCKER_VERSION` to avoid any user confusion about how `DOCKER_VERSION` relates to `DOCKER_API_VERSION`?

**Comment by rgbkrk** [comment]
That's sensible. Patch welcome.

**Comment by carolynvs** [comment]
Sounds like we would first need to update Carina credentials to set the different environment variable.

**Comment by rgbkrk** [comment]
oh d'oh

**Comment by everett-toews** [comment]
@carolynvs Yep. Just wanted to make sure we're all clear on the client side first. I'll bounce this off the Carina team next week too. I could probably do the patch too but don't want to lick this :cookie: just yet.

**Comment by rgbkrk** [comment]
Annoyingly, since we'll have to update the creds files we'll have to support both for a while. Patch it in the backend, patch it in libcarina, patch in dvm. All the while making things work for other users.

Maybe we only fix this when it's actually an issue raised by a confused user (or we notice as a result of multiple users running into it).

**Comment by carolynvs** [comment]
@rgbkrk :+1:

**Comment by everett-toews** [comment]
SGTM

**Comment by rgbkrk** [comment]
Closing since it seems like we're tabling it for a later date.
