### ISSUE TITLE
`brew install´?

### ISSUE THREAD

**Issue by glyph** [getcarina/dvm#85]
It would be nice to `brew install dvm` so it updates along with everything else instead of a custom installer...

**Comment by rgbkrk** [comment]
Yeah... They're fairly opposed to things like `nvm` and other version managers going in. Putting `carina` in and updating it regularly has been easy. Yay for brew! Boo for not maintaining my other version manager.

**Comment by glyph** [comment]
Did you file a PR and it got rejected? `pyenv` is so well-integrated that their help actually specifically mentions `brew` commands to run when you're out of date; I also install `rbenv` from homebrew, and I've never noticed any issues with or animosity towards either.

**Comment by rgbkrk** [comment]
Gosh, I'm way wrong then. It was a passing memory, not sure where I heard it from :wind_chime: We can probably package it up for `brew`, though it will require some refactoring to handle the paths.

**Comment by everett-toews** [comment]
https://community.getcarina.com/t/brew-install-dvm-would-be-awesome/136

**Comment by jeffwidman** [comment]
IIRC, the `nvm` maintainer is opposed to `brew` installation as it added some extra sources of bugs that he didn't want to spend time dealing with.

**Comment by ruurd** [comment]
@jeffwidman nvm IS in brew BTW so? Adding dvm to brew makes life much easier for a lot of people really.

**Comment by carolynvs** [comment]
FYI I am working a brew formula for dvm this week. So it's not a question anymore if we want to do it, just need to get it working and accepted. 😄

**Comment by ruurd** [comment]
\o\\o//o/ :-)

**Comment by everett-toews** [comment]
Link us to the PR here when ready and watch the 👍 roll in!

**Comment by carolynvs** [comment]
When writing the homebrew formula, something else jumped out at me. When `DVM_DIR` is not set, dvm defaults `DVM_DIR` to be the same directory as wherever `dvm.sh` is located.  When dvm is installed with `install.sh`,  the default dvm directory is `~/.dvm`. However with homebrew it ends up defaulting to  `/usr/local/Cellar/dvm`. This is a problem because then the location is tied to the current dvm version.

A quick workaround would be to require that when you use homebrew, you must also explicitly set `DVM_DIR`... but I am not a huge fan of that. It means different config instructions for homebrew users, and if someone forgets to set `DVM_DIR`, they end up with an oddball setup.

I want to change `DVM_DIR` to default to `~/.dvm` when not set explicitly. For anyone who installed with `install.sh`, that changes nothing. If someone lovingly installed dvm some other way, then unless they are explicitly setting `DVM_DIR`, the next time they use dvm, the docker binaries would be re-downloaded.

This is how nvm works, and that's who we based dvm upon originally. Thoughts?

**Comment by ruurd** [comment]
That's the generally accepted way of doing this. Carry on!

**Comment by carolynvs** [comment]
Submitted! https://github.com/Homebrew/homebrew-core/pull/1875

**Comment by glyph** [comment]
Woohoo! Thanks a bunch @carolynvs !

**Comment by ibigbug** [comment]
wow, cool!

**Comment by ruurd** [comment]
Hey Carolyne! I took the liberty to make a small change to the dvm recipe in homebrew. Changed the advice for what to add to .bash_profile to something similar to nvm:

[[ -s "$(brew --prefix dvm)/dvm.sh" ]] && source "$(brew --prefix dvm)/dvm.sh"

**Comment by carolynvs** [comment]
@ruurd Thanks!
